### PR TITLE
Switch to ammonite 1.6.3

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by rdblue** [comment]
All of these changes were required to switch to Ammonite 1.6.3?

Can you please be more clear about your statement that https://github.com/apache/spark/pull/23607 will not work with Ammonite versions after 1.6.0?

If you meant that ammonite-spark doesn't support 1.6.3, as it would appear from this commit, then that is a very different claim.

**Comment by rdblue** [comment]
@alexarchambault, have you had a chance to look into my questions?

**Comment by alexarchambault** [comment]
@rdblue Sorry, I was hoping to catch up with you at the NES. There's nothing to worry about, https://github.com/apache/spark/pull/23607 is not impacted by this, and is fine whatever the Ammonite version.

Only ammonite-spark itself needed a few adjustments when switching from Ammonite 1.6.0 to 1.6.1+.

I had only mentioned Ammonite 1.6.0 in https://github.com/apache/spark/pull/23607 in case anyone would go through the ammonite-spark README, which required Ammonite 1.6.0 at the time.

**Comment by rdblue** [comment]
Thanks for the update! That's what I thought was the case, but on the Spark issue it sounded like the Spark patch was what broke with later versions of Ammonite. I appreciate you taking the time to clarify.

**Pull request merged**
